services:
  - type: web
    name: stackit-qa-platform
    env: node
    plan: free
    buildCommand: npm install
    startCommand: cd Backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true 